Fixing issue #3: Do not re-create packages. o Adding a check to verify that the package file doesn't exist before building. o Adding a -F flag to force the re-building of a package.

diff --git a/build-package b/build-package
--- a/build-package
+++ b/build-package
@@ -3,38 +3,26 @@
 set -e
 #set -x
 
+force=false
+
 usage() {
-  echo "usage: $0 -f [IU | IC] -p [solaris | debian] [-v version] [-u]" >/dev/stderr
+  echo "usage: $0 OPTIONS" >/dev/stderr
+  echo "Use $0 -? for usage help" >/dev/stderr
   exit 1
 }
 
-fetch_latest() {
+find_latest() {
   if [ "$IDEA_URL" = "" ]
   then
     IDEA_URL="http://confluence.jetbrains.net/display/IDEADEV/Maia+EAP"
   fi
 
-  echo "Downloading and parsing... $IDEA_URL"
+  echo "Finding latest version from $IDEA_URL..."
   read url filename version < <(wget -O - -q $IDEA_URL | LC_ALL=C sed -n -e "/.*\"\(http:\/\/.*\/idea$flavor-.*tar.gz\)\".*/ {
     s,.*\"\(http:\/\/.*\/idea$flavor-.*tar.gz\)\".*,\1,p
     s,.*\(ideaI.-[0-9]*.[0-9]*.tar.gz\).*,\1,p
     s,.*-\([0-9]*.[0-9]*\).tar.gz,\1,p
   }" | xargs)
-
-  echo "Latest version is $version, downloading..."
-
-  mkdir -p download
-
-  # It would be possible to use the MD5 sum as a check here, then there would be no need to every force a download
-  #if [ -r "download/$filename" ]
-  #then
-  #  echo "$filename is already downloaded"
-  #else
-  #  echo "Downloading $url..."
-  #  wget -O "download/$filename" $url
-  #fi
-
-  wget -q -P download -N $url
 }
 
 build_common() {
@@ -50,6 +38,22 @@ build_common() {
 
   mkdir -p root/usr/share/applications
   cp intellij-idea.desktop root/usr/share/applications/intellij-idea.desktop
+}
+
+calculate_package_filename() {
+  case "$platform" in
+    solaris)
+      repo=`pwd`/repository/solaris/`uname -p`/`uname -r`
+      mkdir -p $repo
+      package_filename=$repo/intellij-idea-$version-`uname -s``uname -r`-`uname -p`.pkg
+      ;;
+    debian)
+      # TODO: Add arch to the filename (i386, amd64)
+      repo=repository/debian
+      mkdir -p $repo
+      package_filename=$repo/intellij-idea-$FLAVOR_LOWER-$version.deb
+      ;;
+  esac
 }
 
 build_solaris() {
@@ -73,12 +77,9 @@ build_solaris() {
    {printf $1 " " $2 " " $3 " " $4 " " $5 " " $6 " \n"}' >> solaris/prototype
   pkgmk -o -d solaris -f solaris/prototype -r .
 
-  repo=`pwd`/repository/solaris/`uname -p`/`uname -r`
-  mkdir -p $repo
-  pkg_filename=$repo/intellij-idea-$version-`uname -s``uname -r`-`uname -p`.pkg
-  pkgtrans -s solaris $pkg_filename intellij-idea
+  pkgtrans -s solaris $package_filename intellij-idea
   echo "The package was successfully build in solaris/"
-  echo "To install run: pfexec pkgadd -d $pkg_filename"
+  echo "To install run: pfexec pkgadd -d $package_filename"
 
   if [ "$update_repository" = 1 ]
   then
@@ -90,17 +91,6 @@ build_debian() {
   build_common
   mkdir -p root/DEBIAN
 
-  if [ $flavor = "IC" ]
-  then
-    OTHER_FLAVOR_LOWER=iu
-    OTHER_FLAVOR=IU
-    FLAVOR_LOWER=ic
-  else
-    OTHER_FLAVOR_LOWER=ic
-    OTHER_FLAVOR=IC
-    FLAVOR_LOWER=iu
-  fi
-
   sed \
     -e "s,OTHER_FLAVOR_LOWER,$OTHER_FLAVOR_LOWER," \
     -e "s,OTHER_FLAVOR,$OTHER_FLAVOR," \
@@ -109,15 +99,10 @@ build_debian() {
     -e "s,VERSION,$version," \
     control.in > root/DEBIAN/control
 
-  # TODO: Add arch to the filename (i386, amd64)
-  repo=repository/debian
-  mkdir -p $repo
-  deb_filename=$repo/intellij-idea-$FLAVOR_LOWER-$version.deb
-
   echo > fakeroot.save
   FAKEROOT="fakeroot -i fakeroot.save -s fakeroot.save"
   $FAKEROOT -- chown -R root:root root/
-  $FAKEROOT -- dpkg-deb -b root $deb_filename
+  $FAKEROOT -- dpkg-deb -b root $package_filename
 
   if [ "$update_repository" = 1 ]
   then
@@ -136,7 +121,7 @@ then
   fi
 fi
 
-while getopts "f:p:v:u" flag
+while getopts "f:p:v:u?F" flag
 do
   case "$flag" in
     f) 
@@ -161,6 +146,13 @@ do
     u)
       update_repository=1
       ;;
+    F)
+      force="true"
+      ;;
+    ?)
+      less README
+      exit 0
+      ;;
   esac
 done
 
@@ -169,14 +161,61 @@ then
   usage
 fi
 
+if [ $flavor = "IC" ]
+then
+  OTHER_FLAVOR_LOWER=iu
+  OTHER_FLAVOR=IU
+  FLAVOR_LOWER=ic
+else
+  OTHER_FLAVOR_LOWER=ic
+  OTHER_FLAVOR=IC
+  FLAVOR_LOWER=iu
+fi
+
 if [ -z "$version" ]
 then
-  echo "Fetching latest version"
-  fetch_latest
+  find_latest
+  echo "The latest version is $version"
 else
-  echo "Fetching version $version..."
-  wget -q -P download -N http://download.jetbrains.com/idea/idea$flavor-$version.tar.gz
+  url=http://download.jetbrains.com/idea/idea$flavor-$version.tar.gz
   filename=idea$flavor-$version.tar.gz
+fi
+
+calculate_package_filename
+
+if [ -r $package_filename ]
+then
+  if [ $force = "false" ]
+  then
+    echo "The requested version ($version) already exist in the repository, add -F to force a re-build of the package" > /dev/stderr
+    exit 1
+  else
+    echo "WARNING: re-building package for version $version" > /dev/stderr
+  fi
+fi
+
+mkdir -p download
+
+# It would be possible to use the MD5 sum as a check here, then there would be no need to every force a download
+#if [ -r "download/$filename" ]
+#then
+#  echo "$filename is already downloaded"
+#else
+#  echo "Downloading $url..."
+#  wget -O "download/$filename" $url
+#fi
+
+echo "Downloading version $version..."
+if [ `wget -q -P download -N $url; echo $?` != "0" ]
+then
+  echo "Could not download $url" > /dev/stderr
+  exit 1
+fi
+
+if [ ! -r download/$filename ]
+then
+  echo "wget didn't place the downloaded file where expected: download/$filename"
+  exit 1
 fi
 
 case "$platform" in
